[project]
name = "src"
version = "0.0.1"
description = "An mlops demo project"
authors = [{name = "Manish Jangir", email = "work.manishjangiriitg@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}